name: mad_pay_platform_interface
description: A common platform interface for Mad Pay. Сontains cross-platform logic.
version: 2.2.14
repository: https://github.com/MadBrains/Mad-Pay-Flutter
issue_tracker: https://github.com/MadBrains/Mad-Pay-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: "^3.6.0"
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^4.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
